In [2]:
import numpy as np
import cv2

In [7]:
img = cv2.imread('./images/crowd.png')
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [8]:
#Loading cascade classifier called frontal face .... which has already been trained on 6000 plus images
face_cascade = cv2.CascadeClassifier('./cascade_classifier/haarcascade_frontalface_default.xml')
if face_cascade.empty():
    print('Error check the path')
else:
    print('successfull')    

successfull


In [13]:
# Detecting faces with cascade classifier
face_cordinates,num_of_faces = face_cascade.detectMultiScale2(img)
print(face_cordinates)
print(num_of_faces)

[[ 62 114  27  27]
 [136 128  31  31]
 [403 133  30  30]
 [373 158  27  27]
 [ 21 162  27  27]
 [341 194  28  28]
 [244 182  32  32]]
[10  9 16  6  7 12  4]


In [15]:
#drawing the rectange around the detected images
for (rect,stages) in zip(face_cordinates,num_of_faces):
    if stages > 3:
        x,y,w,h = rect
        pt1 = (x,y)
        pt2 = (x+w,y+h)
        img2 = cv2.rectangle(img,pt1,pt2,(0,255,0),2)
cv2.imshow('image',img2)
cv2.waitKey(0)
cv2.destroyAllWindows()        
        
