In [67]:
import numpy as np
import cv2

In [76]:
img = cv2.imread('./images/smile.png')
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [77]:
#Loading cascade classifier called frontal face .... which has already been trained on 6000 plus images
face_cascade = cv2.CascadeClassifier('./cascade_classifier/haarcascade_frontalface_default.xml')
if face_cascade.empty():
    print('Error check the path')
else:
    print('successfull')    

successfull


In [78]:
# Detecting faces with cascade classifier
face_cordinates,num_of_faces = face_cascade.detectMultiScale2(img)
print(face_cordinates)
print(num_of_faces)

[[566 133  91  91]
 [327 138 111 111]
 [415  63 107 107]
 [492 460  65  65]
 [645  88 104 104]
 [162  93 104 104]
 [605 486  57  57]
 [270 209  98  98]
 [217 399  79  79]]
[21 63 42  9 78 42  5  5  4]


In [79]:
#drawing the rectange around the detected images
img2  = img.copy()
for (rect,stages) in zip(face_cordinates,num_of_faces):
    if stages > 3:
        x,y,w,h = rect
        pt1 = (x,y)
        pt2 = (x+w,y+h)
        img2 = cv2.rectangle(img,pt1,pt2,(0,255,0),2)
cv2.imshow('image',img2)
cv2.waitKey(0)
cv2.destroyAllWindows()                

In [82]:
# Eye dectection using cascade classifier
img3 = img.copy()
# In order to detect eyes first we need to detect face using cascade frontal face classifier
face_detect_cascade = cv2.CascadeClassifier('./cascade_classifier/haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier('./cascade_classifier/haarcascade_eye.xml')
smile_cascade = cv2.CascadeClassifier('./cascade_classifier/haarcascade_smile.xml')
if face_detect_cascade.empty():
    print('error reading frontalface_cascade xml')
faces,stages = face_detect_cascade.detectMultiScale2(img3)

for (face,stage) in zip(faces,stages):
    if stage>8:
        x,y,w,h = face
        #crop the numpy array
        crop_face = img3[y:y+h,x:x+w].copy()
        eyes,num_of_eyes = eye_cascade.detectMultiScale2(crop_face)
        for ex,ey,ew,eh in eyes:
            eye_x = ew  // 2 + x+ex
            eye_y =  eh // 2 + y+ey
            cv2.circle(img3,(eye_x,eye_y),(ew+eh)//4,(255,0,0),2)
        smile,num_of_smiles = smile_cascade.detectMultiScale2(crop_face)
        for (smiles,n_smile) in zip(smile,num_of_smiles):
            if n_smile>=20:
                sx,sy,sw,sh= smiles
                pt1 = (sx+x,sy+y)
                pt2 = (x+sw+sx,sh+y+sy)
                cv2.rectangle(img3,pt1,pt2,(0,0,255),2)
cv2.imshow('image',img3)
cv2.waitKey(0)
cv2.destroyAllWindows()            

